<img src="https://images.efollett.com/htmlroot/images/templates/storeLogos/CA/864.gif" style="float: right;"> 




# ECON628-01 
### Midterm - Take Home



---
#### Guidelines 
- This is your notebook for your take home midterm. 
- This part of your midterm, as you might expect, is **more challenging** so I highly recommend you to work ASAP. 

- You are required to submit your answers using this notebook (do not push or submit PDFs, Word docs, etc, cause your answers will be considered invalid = **0%**).
- The take home is **15%** of your total midterm score.
- You can work in groups of no more than **3** students.
- Your code **should not be the same** as the rest of your classmates we will check (trust me on this!!), if your code is the same as any of your classmate **your grade will be penalized.**
- The take home is due on **March 20** before class/exam (if you are taking the in-class exam before the rest of the class, you **need** to push your take home part before you commence with the in-class exam) = **NO EXCUSES !!**
- Use this [link][1] to **submit/include** the GitHub link to your take home exam.
[1]: https://docs.google.com/forms/d/e/1FAIpQLSfLkZJY80tw303ss8Ga_2sUMVgumAppWb4tYwssGTbr879_Mw/viewform "link"
- If you find a piece of code online (from someone else), and you decide to use in your midterm, you need:
    - Cite the website from where you are getting the code.
    - **Explain on your "own words" what the code is doing.**
    - If you fail to do this, your grade will be **penalized.**
- Finally, you don't need to 
---

#### The data

The state of Iowa provides many data sets on their website, we will be using a dataset which contains transactions for all stores that have a class E liquor license. 

The data , data dictionary can be found [directly on their website](https://data.iowa.gov/Economy/Iowa-Liquor-Sales/m3tr-qhgy).

**However,** since many of you may have had computer issues reading medium size datasets, **everyone** needs to use the 10% dataset version of Iowa liquor sales, located in your dataset folder. 

---

#### Package imports

In [1]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import seaborn as sns

import matplotlib
import matplotlib.pyplot as plt

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

plt.style.use('fivethirtyeight')

## 1. Load the data from file

---

In [2]:
Iowa_path= '/Users/abhaindurkar/Desktop/ECON628-01-abhaindurkar/datasets/iowa_liquor/Iowa_Liquor_sales_sample_10pct.csv'

Iowa =pd.read_csv(Iowa_path)

In [3]:
Iowa.head(3)

Date  Store Number         City Zip Code  County Number      County  \
0  11/04/2015          3717       SUMNER    50674            9.0      Bremer   
1  03/02/2016          2614    DAVENPORT    52807           82.0       Scott   
2  02/11/2016          2106  CEDAR FALLS    50613            7.0  Black Hawk   

    Category              Category Name  Vendor Number  Item Number  \
0  1051100.0           APRICOT BRANDIES             55        54436   
1  1011100.0           BLENDED WHISKIES            395        27605   
2  1011200.0  STRAIGHT BOURBON WHISKIES             65        19067   

            Item Description  Bottle Volume (ml) State Bottle Cost  \
0  Mr. Boston Apricot Brandy                 750             $4.50   
1                    Tin Cup                 750            $13.75   
2                   Jim Beam                1000            $12.59   

  State Bottle Retail  Bottles Sold Sale (Dollars)  Volume Sold (Liters)  \
0               $6.75            12         $81.00                   9.0   
1              $20.63             2         $41.26                   1.5   
2              $18.89            24        $453.36                  24.0   

   Volume Sold (Gallons)  
0                   2.38  
1                   0.40  
2                   6.34

In [4]:
Iowa.tail(4)

Date  Store Number             City Zip Code  County Number  \
270951  11/04/2015          5151        IDA GROVE    51445           47.0   
270952  10/20/2015          5152         WATERLOO    50702            7.0   
270953  11/20/2015          3562  WEST BURLINGTON    52655           29.0   
270954  01/27/2015          4446        URBANDALE    50322           77.0   

            County   Category                       Category Name  \
270951         Ida  1011200.0           STRAIGHT BOURBON WHISKIES   
270952  Black Hawk  1011300.0                  TENNESSEE WHISKIES   
270953  Des Moines  1082900.0  MISC. IMPORTED CORDIALS & LIQUEURS   
270954        Polk  1031080.0                      VODKA 80 PROOF   

        Vendor Number  Item Number               Item Description  \
270951            259        17956      Evan Williams Str Bourbon   
270952             85        26826  Jack Daniels Old #7 Black Lbl   
270953            192        65258           Jagermeister Liqueur   
270954            260        37993          Smirnoff Vodka 80 Prf   

        Bottle Volume (ml) State Bottle Cost State Bottle Retail  \
270951                 750             $7.47              $11.21   
270952                 750            $15.07              $22.61   
270953                1750            $26.05              $39.08   
270954                 200             $2.75               $4.13   

        Bottles Sold Sale (Dollars)  Volume Sold (Liters)  \
270951             3         $33.63                  2.25   
270952             6        $135.66                  4.50   
270953             6        $234.48                 10.50   
270954             8         $33.04                  1.60   

        Volume Sold (Gallons)  
270951                   0.59  
270952                   1.19  
270953                   2.77  
270954                   0.42

## 2. Do an initial overview of the data

---

At the very least describe the columns/variables and the datatypes. 

In [5]:
Iowa.describe()

C:\Users\abhaindurkar\Anaconda3\New folder\envs\econ\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


Store Number  County Number      Category  Vendor Number  \
count  270955.000000  269878.000000  2.708870e+05   270955.00000   
mean     3590.263701      57.231642  1.043888e+06      256.43443   
std       947.662050      27.341205  5.018211e+04      141.01489   
min      2106.000000       1.000000  1.011100e+06       10.00000   
25%      2604.000000            NaN           NaN      115.00000   
50%      3722.000000            NaN           NaN      260.00000   
75%      4378.000000            NaN           NaN      380.00000   
max      9023.000000      99.000000  1.701100e+06      978.00000   

         Item Number  Bottle Volume (ml)   Bottles Sold  Volume Sold (Liters)  \
count  270955.000000       270955.000000  270955.000000         270955.000000   
mean    45974.963300          924.830341       9.871285              8.981351   
std     52757.043086          493.088489      24.040912             28.913690   
min       168.000000           50.000000       1.000000              0.100000   
25%     26827.000000          750.000000       2.000000              1.500000   
50%     38176.000000          750.000000       6.000000              5.250000   
75%     64573.000000         1000.000000      12.000000             10.500000   
max    995507.000000         6000.000000    2508.000000           2508.000000   

       Volume Sold (Gallons)  
count          270955.000000  
mean                2.372830  
std                 7.638182  
min                 0.030000  
25%                 0.400000  
50%                 1.390000  
75%                 2.770000  
max               662.540000

In [6]:
Iowa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270955 entries, 0 to 270954
Data columns (total 18 columns):
Date                     270955 non-null object
Store Number             270955 non-null int64
City                     270955 non-null object
Zip Code                 270955 non-null object
County Number            269878 non-null float64
County                   269878 non-null object
Category                 270887 non-null float64
Category Name            270323 non-null object
Vendor Number            270955 non-null int64
Item Number              270955 non-null int64
Item Description         270955 non-null object
Bottle Volume (ml)       270955 non-null int64
State Bottle Cost        270955 non-null object
State Bottle Retail      270955 non-null object
Bottles Sold             270955 non-null int64
Sale (Dollars)           270955 non-null object
Volume Sold (Liters)     270955 non-null float64
Volume Sold (Gallons)    270955 non-null float64
dtypes: float64(4), int64(

In [7]:
Iowa.shape

(270955, 18)

Just Visualizing, the columns and what the data looks like


## 3. Clean the dataset

---

### 3.1 Identify columns that you will need to convert and clean. Where and how is the data corrupted?

Don't worry about converting the date column to a pandas/numpy "datetime" datatype, unless you want to (not required for these problems and is a challenging thing to work with in its own right.)

In [8]:
Iowa[ pd.isnull(Iowa['County Number'])]

Date  Store Number           City Zip Code  County Number  \
135     01/20/2016          5222   CEDAR RAPIDS    52402            NaN   
198     03/02/2016          3820     SIOUX CITY    51103            NaN   
272     03/21/2016          4222      EVANSDALE    50707            NaN   
290     03/21/2016          5236        ANAMOSA    52205            NaN   
321     02/23/2016          4203        WAVERLY    50677            NaN   
863     01/11/2016          2460        HAMPTON    50441            NaN   
964     05/19/2015          4247        BELMOND    50421            NaN   
982     03/30/2016          5222   CEDAR RAPIDS    52402            NaN   
1024    03/23/2016          3820     SIOUX CITY    51103            NaN   
1630    02/10/2016          5224     CORALVILLE    52241            NaN   
1667    03/30/2016          2637      DAVENPORT    52804            NaN   
1798    03/03/2016          5227        CLINTON    52732            NaN   
2084    03/24/2016          5229        NORWALK    50211            NaN   
2176    03/21/2016          5236        ANAMOSA    52205            NaN   
2533    03/09/2016          2637      DAVENPORT    52804            NaN   
2549    03/22/2016          5210       CLARINDA    51632            NaN   
2678    03/29/2016          5210       CLARINDA    51632            NaN   
2871    09/22/2015          4247        BELMOND    50421            NaN   
3246    03/16/2016          3820     SIOUX CITY    51103            NaN   
3939    03/21/2016          5236        ANAMOSA    52205            NaN   
4015    03/16/2016          2637      DAVENPORT    52804            NaN   
4448    03/03/2015          4247        BELMOND    50421            NaN   
4780    03/30/2016          5225  NORTH LIBERTY    52317            NaN   
5893    03/09/2016          5233  PLEASANTVILLE    50225            NaN   
6265    03/16/2016          2238        ALTOONA    50009            NaN   
6487    01/25/2016          2460        HAMPTON    50441            NaN   
7249    03/16/2016          3820     SIOUX CITY    51103            NaN   
7585    03/08/2016          4203        WAVERLY    50677            NaN   
7834    03/17/2015          4247        BELMOND    50421            NaN   
8186    03/14/2016          4307         DUNLAP    712-2            NaN   
...            ...           ...            ...      ...            ...   
261605  01/06/2016          3682         WESLEY    50483            NaN   
261873  03/22/2016          5237     FORT DODGE    50501            NaN   
262035  03/21/2016          5226      DAVENPORT    52802            NaN   
262394  01/25/2016          2460        HAMPTON    50441            NaN   
262521  10/13/2015          4247        BELMOND    50421            NaN   
262547  03/31/2016          5247       ROCKWELL    50469            NaN   
263730  01/05/2016          5210       CLARINDA    51632            NaN   
263920  02/16/2016          5230   CEDAR RAPIDS    52402            NaN   
263934  10/13/2015          4247        BELMOND    50421            NaN   
264281  03/16/2016          2637      DAVENPORT    52804            NaN   
264975  03/28/2016          2460        HAMPTON    50441            NaN   
265388  02/10/2016          5225  NORTH LIBERTY    52317            NaN   
266383  09/08/2015          4247        BELMOND    50421            NaN   
266660  03/02/2016          3820     SIOUX CITY    51103            NaN   
266801  03/03/2016          5220     MASON CITY    50401            NaN   
266806  03/22/2016          4006      LARCHWOOD    51241            NaN   
266961  03/21/2016          2650         HARLAN    51537            NaN   
267729  03/07/2016          2650         HARLAN    51537            NaN   
268186  02/08/2016          5214   CEDAR RAPIDS    52404            NaN   
268475  02/16/2016          5230   CEDAR RAPIDS    52402            NaN   
268504  02/23/2016          4247        BELMOND    50421            NaN   
269000  01/25/2016          2460       

In [9]:
Iowa[ pd.isnull(Iowa['Volume Sold (Liters)'])]

Empty DataFrame
Columns: [Date, Store Number, City, Zip Code, County Number, County, Category, Category Name, Vendor Number, Item Number, Item Description, Bottle Volume (ml), State Bottle Cost, State Bottle Retail, Bottles Sold, Sale (Dollars), Volume Sold (Liters), Volume Sold (Gallons)]
Index: []

In [10]:
Iowa[ pd.isnull(Iowa['Category'])]

Date  Store Number             City Zip Code  County Number  \
6744    11/16/2015          4857  WEST BURLINGTON    52655           29.0   
11241   10/27/2015          3625           ANKENY    50021           77.0   
16205   10/12/2015          2670       CORALVILLE    52241           52.0   
17648   11/19/2015          2567        DAVENPORT    52806           82.0   
18996   11/19/2015          3664        NORTHWOOD    50459           98.0   
24190   10/20/2015          5097     CEDAR RAPIDS    52402           57.0   
29798   10/12/2015          2643         WATERLOO    50701            7.0   
34063   10/13/2015          2666           ANKENY    50023           77.0   
35894   10/14/2015          5067       STORM LAKE    50588           11.0   
37974   10/14/2015          3735        OSKALOOSA    52577           10.0   
44595   10/28/2015          2513        IOWA CITY    52240           52.0   
48348   11/18/2015          3735        OSKALOOSA    52577           10.0   
49712   10/12/2015          3833         ATLANTIC    50022           15.0   
53329   10/13/2015          2597         CHEROKEE    51012           18.0   
54674   10/13/2015          2552     CEDAR RAPIDS    52404           57.0   
55347   11/16/2015          2584     FORT MADISON    52627           56.0   
57995   10/14/2015          3819          DECORAH    52101           96.0   
59896   04/06/2015          2601        FAIRFIELD    52556           51.0   
60370   10/26/2015          3628     CEDAR RAPIDS    52402           57.0   
67879   10/27/2015          2544     MARSHALLTOWN    50158           64.0   
69822   10/12/2015          3868           MARION    52302           57.0   
73365   11/17/2015          3942           TOLEDO    52342           86.0   
76148   11/21/2015          2518          RED OAK    51566           69.0   
82278   11/21/2015          2552     CEDAR RAPIDS    52404           57.0   
85858   11/19/2015          3732         ELDRIDGE    52748           82.0   
87425   11/16/2015          4910         WATERLOO    50702            7.0   
89897   08/10/2015          3549     FORT MADISON    52627           56.0   
91043   02/08/2016          4604           NEWTON    50208           50.0   
91606   07/13/2015          5102     MOUNT VERNON    52314           57.0   
93441   10/12/2015          4114         ATLANTIC    50022           15.0   
...            ...           ...              ...      ...            ...   
138964  10/28/2015          2637        DAVENPORT    52804           82.0   
142979  11/09/2015          2653       WASHINGTON    52353           92.0   
143721  11/23/2015          3853        DAVENPORT    52804           82.0   
144863  11/16/2015          2549        INDIANOLA    50125           91.0   
147629  11/02/2015          2653       WASHINGTON    52353           92.0   
149016  11/17/2015          3813        MOUNT AYR    50854           80.0   
153207  10/14/2015          4156          OELWEIN    50662           33.0   
157682  11/16/2015          2643         WATERLOO    50701            7.0   
157851  11/23/2015          2594       SIOUX CITY    51106           97.0   
158669  10/15/2015          5063         WATERLOO    50703            7.0   
178003  10/12/2015          2648  WEST DES MOINES    50265           77.0   
178533  10/14/2015          4947      CEDAR FALLS    50647            7.0   
186733  10/13/2015          2624          DUBUQUE    52002           31.0   
192015  10/20/2015          2509     CEDAR RAPIDS    52404           57.0   
196086  11/02/2015          2662        MUSCATINE    52761           70.0   
210035  10/13/2015          2518          RED OAK    51566           69.0   
216414  11/30/2015          2636       DES MOINES    50317           77.0   
216660  10/22/2015          3713       MASON CITY    50401           17.0   
221370  10/12/2015          3934        MAQUOKETA    52060           49.0   
224617  10/15/2015          3647          CLINTON    52732           23.0   
224979  10

### 3.2 Clean the columns

In [11]:
Iowa['State Bottle Cost']=Iowa['State Bottle Cost'].str.replace('$','')

In [12]:
Iowa['State Bottle Retail']=Iowa['State Bottle Retail'].str.replace('$','')

In [13]:
Iowa['Sale (Dollars)']=Iowa['Sale (Dollars)'].str.replace('$','')

In [14]:
Iowa.head(10)


Date  Store Number          City Zip Code  County Number  \
0  11/04/2015          3717        SUMNER    50674            9.0   
1  03/02/2016          2614     DAVENPORT    52807           82.0   
2  02/11/2016          2106   CEDAR FALLS    50613            7.0   
3  02/03/2016          2501          AMES    50010           85.0   
4  08/18/2015          3654       BELMOND    50421           99.0   
5  04/20/2015          2569  CEDAR RAPIDS    52402           57.0   
6  08/05/2015          2596       OTTUMWA    52501           90.0   
7  06/25/2015          3456    CLEAR LAKE    50428           17.0   
8  01/04/2016          4757     BONDURANT    50035           77.0   
9  11/10/2015          4346    SHELLSBURG    52332            6.0   

        County   Category              Category Name  Vendor Number  \
0       Bremer  1051100.0           APRICOT BRANDIES             55   
1        Scott  1011100.0           BLENDED WHISKIES            395   
2   Black Hawk  1011200.0  STRAIGHT BOURBON WHISKIES             65   
3        Story  1071100.0         AMERICAN COCKTAILS            395   
4       Wright  1031080.0             VODKA 80 PROOF            297   
5         Linn  1041100.0          AMERICAN DRY GINS            205   
6      Wapello  1051010.0    AMERICAN GRAPE BRANDIES             85   
7  Cerro Gordo  1012100.0          CANADIAN WHISKIES             65   
8         Polk  1032080.0             IMPORTED VODKA            370   
9       Benton  1081315.0          CINNAMON SCHNAPPS             65   

   Item Number              Item Description  Bottle Volume (ml)  \
0        54436     Mr. Boston Apricot Brandy                 750   
1        27605                       Tin Cup                 750   
2        19067                      Jim Beam                1000   
3        59154       1800 Ultimate Margarita                1750   
4        35918            Five O'clock Vodka                1750   
5        31473             New Amsterdam Gin                1750   
6        52806                 Korbel Brandy                 750   
7        10628          Canadian Club Whisky                1750   
8        34006  Absolut Swedish Vodka 80 Prf                 750   
9        82610            Dekuyper Hot Damn!                1000   

  State Bottle Cost State Bottle Retail  Bottles Sold Sale (Dollars)  \
0              4.50                6.75            12          81.00   
1             13.75               20.63             2          41.26   
2             12.59               18.89            24         453.36   
3              9.50               14.25             6          85.50   
4              7.20               10.80            12         129.60   
5             13.32               19.98             6         119.88   
6              6.66                9.99             3          29.97   
7             15.75               23.63             2          47.26   
8             11.49               17.24             4          68.96   
9              7.62               11.43             2          22.86   

   Volume Sold (Liters)  Volume Sold (Gallons)  
0                  9.00                   2.38  
1                  1.50                   0.40  
2                 24.00                   6.34  
3                 10.50                   2.77  
4                 21.00                   5.55  
5                 10.50                   2.77  
6                  2.25                   0.59  
7                  3.50                   0.92  
8                  3.00                   0.79  
9                  2.00                   0.53

In [15]:
Iowa["State Bottle Cost"]= pd.to_numeric(Iowa["State Bottle Cost"],
                                         errors="coerce")

Iowa["State Bottle Retail"]= pd.to_numeric(Iowa["State Bottle Retail"],
                                         errors="coerce")
Iowa["Sale (Dollars)"]= pd.to_numeric(Iowa["Sale (Dollars)"],
                                         errors="coerce")


### 3.3 Perform more extensive cleaning of the dataset

Cleaning of data can mean a lot more than just fixing strings and numbers in columns. There are often logical errors with data, useless or nonsensical categories, redundancy of information, outliers, and many more problems.

This dataset has problems beyond just fixing the types of columns. Keep in mind that some types of "data cleaning" is subjective: it's not always a cut-and-dry conversion of type or removal of null values. Subjectivity when dealing with data is just a fact of life when dealing with data. This isn't a kind of programming where things are just right or wrong.

In [16]:
Iowa.drop(['Vendor Number',], axis=1, inplace=True)

In [17]:
Iowa.drop(['County Number',], axis=1, inplace=True)


### 4. Filter/adjust the store data

---

Some stores may have opened or closed in 2015. These stores will have incorrect yearly summary statistics since they were not open the full year. We need to filter them out or find another way to deal with the inconsistent numbers of months across stores.

It is up to you how you want to deal with this problem.

1. Investigate problematic stores.
2. Decide on an approach to deal with stores not open for the full 2015 year.
3. Implement your plan.
4. Briefly report on what you did and why.


In [18]:
Iowa['Date'] = pd.to_datetime(Iowa['Date'])
Iowa['Month'] = Iowa['Date'].dt.month
Iowa['Year']=Iowa['Date'].dt.year
Iowa.head()

Date  Store Number         City Zip Code      County   Category  \
0 2015-11-04          3717       SUMNER    50674      Bremer  1051100.0   
1 2016-03-02          2614    DAVENPORT    52807       Scott  1011100.0   
2 2016-02-11          2106  CEDAR FALLS    50613  Black Hawk  1011200.0   
3 2016-02-03          2501         AMES    50010       Story  1071100.0   
4 2015-08-18          3654      BELMOND    50421      Wright  1031080.0   

               Category Name  Item Number           Item Description  \
0           APRICOT BRANDIES        54436  Mr. Boston Apricot Brandy   
1           BLENDED WHISKIES        27605                    Tin Cup   
2  STRAIGHT BOURBON WHISKIES        19067                   Jim Beam   
3         AMERICAN COCKTAILS        59154    1800 Ultimate Margarita   
4             VODKA 80 PROOF        35918         Five O'clock Vodka   

   Bottle Volume (ml)  State Bottle Cost  State Bottle Retail  Bottles Sold  \
0                 750               4.50                 6.75            12   
1                 750              13.75                20.63             2   
2                1000              12.59                18.89            24   
3                1750               9.50                14.25             6   
4                1750               7.20                10.80            12   

   Sale (Dollars)  Volume Sold (Liters)  Volume Sold (Gallons)  Month  Year  
0           81.00                   9.0                   2.38     11  2015  
1           41.26                   1.5                   0.40      3  2016  
2          453.36                  24.0                   6.34      2  2016  
3           85.50                  10.5                   2.77      2  2016  
4          129.60                  21.0                   5.55      8  2015

In [19]:
Iowa.describe()

Store Number      Category    Item Number  Bottle Volume (ml)  \
count  270955.000000  2.708870e+05  270955.000000       270955.000000   
mean     3590.263701  1.043888e+06   45974.963300          924.830341   
std       947.662050  5.018211e+04   52757.043086          493.088489   
min      2106.000000  1.011100e+06     168.000000           50.000000   
25%      2604.000000           NaN   26827.000000          750.000000   
50%      3722.000000           NaN   38176.000000          750.000000   
75%      4378.000000           NaN   64573.000000         1000.000000   
max      9023.000000  1.701100e+06  995507.000000         6000.000000   

       State Bottle Cost  State Bottle Retail   Bottles Sold  Sale (Dollars)  \
count      270955.000000        270955.000000  270955.000000   270955.000000   
mean            9.773281            14.675760       9.871285      128.902375   
std             7.047119            10.570145      24.040912      383.027369   
min             0.890000             1.340000       1.000000        1.340000   
25%             5.500000             8.270000       2.000000       30.450000   
50%             8.000000            12.270000       6.000000       70.560000   
75%            11.920000            17.880000      12.000000      135.000000   
max           425.000000           637.500000    2508.000000    36392.400000   

       Volume Sold (Liters)  Volume Sold (Gallons)          Month  \
count         270955.000000          270955.000000  270955.000000   
mean               8.981351               2.372830       5.821103   
std               28.913690               7.638182       3.621291   
min                0.100000               0.030000       1.000000   
25%                1.500000               0.400000       3.000000   
50%                5.250000               1.390000       5.000000   
75%               10.500000               2.770000       9.000000   
max             2508.000000             662.540000      12.000000   

                Year  
count  270955.000000  
mean     2015.193246  
std         0.394845  
min      2015.000000  
25%      2015.000000  
50%      2015.000000  
75%      2015.000000  
max      2016.000000

In [20]:
Iowa2015=Iowa[Iowa['Year']==2015]


In [21]:
Iowa2015.head(10)

Date  Store Number             City Zip Code       County   Category  \
0  2015-11-04          3717           SUMNER    50674       Bremer  1051100.0   
4  2015-08-18          3654          BELMOND    50421       Wright  1031080.0   
5  2015-04-20          2569     CEDAR RAPIDS    52402         Linn  1041100.0   
6  2015-08-05          2596          OTTUMWA    52501      Wapello  1051010.0   
7  2015-06-25          3456       CLEAR LAKE    50428  Cerro Gordo  1012100.0   
9  2015-11-10          4346       SHELLSBURG    52332       Benton  1081315.0   
10 2015-09-28          2648  WEST DES MOINES    50265         Polk  1011250.0   
11 2015-10-28          2600        OSKALOOSA    52577      Mahaska  1071100.0   
12 2015-01-22          3858        DAVENPORT    52806        Scott  1012100.0   
15 2015-06-10          3717           SUMNER    50674       Bremer  1051100.0   

                     Category Name  Item Number  \
0                 APRICOT BRANDIES        54436   
4                   VODKA 80 PROOF        35918   
5                AMERICAN DRY GINS        31473   
6          AMERICAN GRAPE BRANDIES        52806   
7                CANADIAN WHISKIES        10628   
9                CINNAMON SCHNAPPS        82610   
10  SINGLE BARREL BOURBON WHISKIES        19235   
11              AMERICAN COCKTAILS        57148   
12               CANADIAN WHISKIES        15248   
15                APRICOT BRANDIES        54436   

                    Item Description  Bottle Volume (ml)  State Bottle Cost  \
0          Mr. Boston Apricot Brandy                 750               4.50   
4                 Five O'clock Vodka                1750               7.20   
5                  New Amsterdam Gin                1750              13.32   
6                      Korbel Brandy                 750               6.66   
7               Canadian Club Whisky                1750              15.75   
9                 Dekuyper Hot Damn!                1000               7.62   
10  Knob Creek Single Barrel Reserve                 750              26.24   
11     Chi-Chi's Margarita W/tequila                1750               6.00   
12              Windsor Canadian Pet                1750               8.92   
15         Mr. Boston Apricot Brandy                 750               4.50   

    State Bottle Retail  Bottles Sold  Sale (Dollars)  Volume Sold (Liters)  \
0                  6.75            12           81.00                  9.00   
4                 10.80            12          129.60                 21.00   
5                 19.98             6          119.88                 10.50   
6                  9.99             3           29.97                  2.25   
7                 23.63             2           47.26                  3.50   
9                 11.43             2           22.86                  2.00   
10                39.36             6          236.16                  4.50   
11                 9.25             6           55.50                 10.50   
12                13.38             1           13.38                  1.75   
15                 6.75             4           27.00                  3.00   

    Volume Sold (Gallons)  Month  Year  
0                    2.38     11  2015  
4                    5.55      8  2015  
5                    2.77      4  2015  
6                    0.59      8  2015  
7                    0.92      6  2015  
9                    0.53     11  2015  
10                   1.19      9  2015  
11                   2.77     10  2015  
12                   0.46      1  2015  
15                   0.79      6  2015

In [22]:
Iowa2015.groupby(['Store Number', 'Month'])['Sale (Dollars)','Volume Sold (Liters)', 'Volume Sold (Gallons)'].count()

Sale (Dollars)  Volume Sold (Liters)  \
Store Number Month                                         
2106         1                  44                    44   
             2                  42                    42   
             3                  43                    43   
             4                  44                    44   
             5                  41                    41   
             6                  46                    46   
             7                  52                    52   
             8                  40                    40   
             9                  41                    41   
             10                 54                    54   
             11                 35                    35   
             12                 45                    45   
2113         1                  15                    15   
             2                   9                     9   
             3                  18                    18   
             4                   6                     6   
             5                  10                    10   
             6                  16                    16   
             7                  10                    10   
             8                   7                     7   
             9                  17                    17   
             10                 11                    11   
             11                 11                    11   
             12                 17                    17   
2130         1                  23                    23   
             2                  30                    30   
             3                  34                    34   
             4                  43                    43   
             5                  33                    33   
             6                  27                    27   
...                            ...                   ...   
9001         5                   2                     2   
             7                   4                     4   
             8                   5                     5   
             10                  1                     1   
             12                  4                     4   
9002         1                   3                     3   
             2                   3                     3   
             3                   3                     3   
             4                   5                     5   
             5                   1                     1   
             6                   5                     5   
             7                   6                     6   
             8                   1                     1   
             9                   4                     4   
             10                  3                     3   
             11                  5                     5   
             12                  5                     5   
9010         1                   2                     2   
             2                   4                     4   
             3                   2                     2   
             4                   2                     2   
             5                   1                     1   
             6                   1                     1   
             8                   2                     2   
             9                   2                     2   
9013         6                   1                     1   
             8                   1                     1   
             11                  1                     1   
             12                  1                     1   
9018         10                  1                     1   

                    Volume Sold (Gallons)  
Store Number Month                         
2106         1                         44  
             2                         42  
             3                         43  
             4     

Here we can see that all the stores do not have data for all the months, some have less than 12 months, these are the problematic stores.

In [23]:
Iowamonthcount=Iowa2015.groupby(['Store Number'])['Month'].count()


In [24]:
Storesdata=Iowa2015.groupby(['Store Number', 'Month'])['Sale (Dollars)','Volume Sold (Liters)', 'Volume Sold (Gallons)'].count()

In [25]:
Iowa2015['Store Number'].unique()


array([3717, 3654, 2569, ..., 5215, 5201, 4778], dtype=int64)

In [26]:
Iowa2015['Month'].unique()

array([11,  8,  4,  6,  9, 10,  1, 12,  3,  2,  7,  5], dtype=int64)

In [27]:
Iowa2015.sort(['Store Number'],ascending=[True])

C:\Users\abhaindurkar\Anaconda3\New folder\envs\econ\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


Date  Store Number         City Zip Code      County   Category  \
137952 2015-09-17          2106  CEDAR FALLS    50613  Black Hawk  1081390.0   
180052 2015-01-29          2106  CEDAR FALLS    50613  Black Hawk  1031200.0   
144658 2015-06-11          2106  CEDAR FALLS    50613  Black Hawk  1081200.0   
241525 2015-03-05          2106  CEDAR FALLS    50613  Black Hawk  1011250.0   
80368  2015-05-21          2106  CEDAR FALLS    50613  Black Hawk  1012200.0   
41290  2015-11-12          2106  CEDAR FALLS    50613  Black Hawk  1031200.0   
57177  2015-01-22          2106  CEDAR FALLS    50613  Black Hawk  1081200.0   
130957 2015-01-08          2106  CEDAR FALLS    50613  Black Hawk  1081317.0   
13533  2015-01-15          2106  CEDAR FALLS    50613  Black Hawk  1012300.0   
257998 2015-11-19          2106  CEDAR FALLS    50613  Black Hawk  1012100.0   
9057   2015-04-09          2106  CEDAR FALLS    50613  Black Hawk  1031200.0   
25587  2015-05-21          2106  CEDAR FALLS    50613  Black Hawk  1042100.0   
130870 2015-01-15          2106  CEDAR FALLS    50613  Black Hawk  1081315.0   
231523 2015-12-03          2106  CEDAR FALLS    50613  Black Hawk  1081312.0   
109536 2015-12-10          2106  CEDAR FALLS    50613  Black Hawk  1081390.0   
216247 2015-02-05          2106  CEDAR FALLS    50613  Black Hawk  1012100.0   
194151 2015-06-11          2106  CEDAR FALLS    50613  Black Hawk  1022100.0   
144988 2015-07-01          2106  CEDAR FALLS    50613  Black Hawk  1081390.0   
2348   2015-07-30          2106  CEDAR FALLS    50613  Black Hawk  1081390.0   
41773  2015-03-12          2106  CEDAR FALLS    50613  Black Hawk  1082900.0   
230833 2015-10-22          2106  CEDAR FALLS    50613  Black Hawk  1081390.0   
258145 2015-01-29          2106  CEDAR FALLS    50613  Black Hawk  1012200.0   
30502  2015-12-17          2106  CEDAR FALLS    50613  Black Hawk  1081240.0   
130262 2015-06-25          2106  CEDAR FALLS    50613  Black Hawk  1081335.0   
25662  2015-09-10          2106  CEDAR FALLS    50613  Black Hawk  1031080.0   
2512   2015-01-22          2106  CEDAR FALLS    50613  Black Hawk  1041100.0   
95733  2015-05-28          2106  CEDAR FALLS    50613  Black Hawk  1062300.0   
165735 2015-10-01          2106  CEDAR FALLS    50613  Black Hawk  1012300.0   
179201 2015-07-30          2106  CEDAR FALLS    50613  Black Hawk  1031080.0   
80570  2015-01-08          2106  CEDAR FALLS    50613  Black Hawk  1062200.0   
...           ...           ...          ...      ...         ...        ...   
250032 2015-12-23          9002     LECLAIRE    52753       Scott  1011100.0   
150609 2015-08-13          9002     LECLAIRE    52753       Scott  1031080.0   
121947 2015-12-31          9002     LECLAIRE    52753       Scott  1081200.0   
23470  2015-09-03          9002     LECLAIRE    52753       Scott  1011200.0   
221484 2015-01-22          9002     LECLAIRE    52753       Scott  1041100.0   
262952 2015-05-28          9002     LECLAIRE    52753       Scott  1031200.0   
235634 2015-09-17          9002     LECLAIRE    52753       Scott  1011100.0   
236463 2015-11-05          9002     LECLAIRE    52753       Scott  1031080.0   
164148 2015-06-18          9002     LECLAIRE    52753       Scott  1031080.0   
141678 2015-05-20          9010      NORWALK    50211      Warren  1081600.0   
91949  2015-08-06          9010      NORWALK    50211      Warren  1081900.0   
128323 2015-06-16          9010      NORWALK    50211      Warren  1011100.0   
244748 2015-02-09          9010      NORWALK    50211      Warren  1081900.0   
172628 2015-04-23          9010      NORWALK    50211      Warren  1011100.0   
16295  2015-01-20          9010      NORWALK    50211      Warren  1081600.0   
135891 2015-02-09          9010      NORWALK    50211      Warren  1081900.0   
267581 2015-01-20          9010      NORWALK    50211      Warren  1011100.0   
178774 2015-02-09          9010      NORWALK    50211      Warren  1051010.0   
269367 2015-0

In [28]:
# Create a dataframe summing up sales by month, and store
Iowa2015monthsales = Iowa2015.groupby(['Store Number', 'Month'])['Sale (Dollars)'].sum().reset_index()
Iowa2015monthsales.head(15)

Store Number  Month  Sale (Dollars)
0           2106      1        13567.80
1           2106      2        12873.14
2           2106      3        12846.35
3           2106      4        11957.86
4           2106      5         7526.88
5           2106      6        11688.72
6           2106      7        15764.34
7           2106      8        12329.82
8           2106      9        10230.61
9           2106     10        16899.33
10          2106     11        10688.38
11          2106     12         9952.99
12          2113      1          813.68
13          2113      2          713.59
14          2113      3         1305.98

Now we have monthly sales of each store


In [29]:
Iowa2015monthsales['salesdummy'] = Iowa2015monthsales['Sale (Dollars)']
Iowa2015monthsales.loc[Iowa2015monthsales.salesdummy > 0 , 'salesdummy'] = 1

Iowa2015monthsales.head(30)

Store Number  Month  Sale (Dollars)  salesdummy
0           2106      1        13567.80         1.0
1           2106      2        12873.14         1.0
2           2106      3        12846.35         1.0
3           2106      4        11957.86         1.0
4           2106      5         7526.88         1.0
5           2106      6        11688.72         1.0
6           2106      7        15764.34         1.0
7           2106      8        12329.82         1.0
8           2106      9        10230.61         1.0
9           2106     10        16899.33         1.0
10          2106     11        10688.38         1.0
11          2106     12         9952.99         1.0
12          2113      1          813.68         1.0
13          2113      2          713.59         1.0
14          2113      3         1305.98         1.0
15          2113      4          414.15         1.0
16          2113      5          727.69         1.0
17          2113      6          852.46         1.0
18          2113      7          782.97         1.0
19          2113      8          184.47         1.0
20          2113      9         1146.12         1.0
21          2113     10          862.29         1.0
22          2113     11          397.05         1.0
23          2113     12         1109.77         1.0
24          2130      1         7725.66         1.0
25          2130      2         8655.08         1.0
26          2130      3         7891.83         1.0
27          2130      4        13738.75         1.0
28          2130      5        13612.92         1.0
29          2130      6         7686.42         1.0

In [30]:
Iowa2015salesdummies = Iowa2015monthsales.groupby(['Store Number'])['salesdummy'].sum().reset_index()

Iowa2015salesdummies.head(40)

Store Number  salesdummy
0           2106        12.0
1           2113        12.0
2           2130        12.0
3           2152        12.0
4           2178        12.0
5           2190        12.0
6           2191        12.0
7           2200        12.0
8           2205        12.0
9           2228        12.0
10          2233        12.0
11          2238        11.0
12          2248        12.0
13          2285        12.0
14          2290        12.0
15          2327        12.0
16          2353        12.0
17          2367         6.0
18          2413        12.0
19          2445        12.0
20          2448        12.0
21          2459        12.0
22          2460        12.0
23          2465        12.0
24          2475        12.0
25          2478        12.0
26          2487        11.0
27          2498        11.0
28          2500        12.0
29          2501        12.0
30          2502        12.0
31          2505        12.0
32          2506        12.0
33          2507        12.0
34          2508        12.0
35          2509        12.0
36          2512        12.0
37          2513        12.0
38          2514        12.0
39          2515        12.0

Here we can see the problematic stores that have data less than 12 months.

In [31]:
Iowa2015new = Iowa2015.merge(Iowa2015salesdummies, left_on='Store Number', right_on='Store Number', how='outer')

Iowa2015new.head(50)

Date  Store Number    City Zip Code  County   Category  \
0  2015-11-04          3717  SUMNER    50674  Bremer  1051100.0   
1  2015-06-10          3717  SUMNER    50674  Bremer  1051100.0   
2  2015-01-21          3717  SUMNER    50674  Bremer  1081900.0   
3  2015-11-11          3717  SUMNER    50674  Bremer  1012100.0   
4  2015-01-07          3717  SUMNER    50674  Bremer  1011200.0   
5  2015-02-18          3717  SUMNER    50674  Bremer  1012300.0   
6  2015-08-19          3717  SUMNER    50674  Bremer  1062300.0   
7  2015-12-09          3717  SUMNER    50674  Bremer  1012100.0   
8  2015-02-04          3717  SUMNER    50674  Bremer  1081200.0   
9  2015-12-22          3717  SUMNER    50674  Bremer  1031200.0   
10 2015-04-29          3717  SUMNER    50674  Bremer  1012100.0   
11 2015-10-28          3717  SUMNER    50674  Bremer  1081370.0   
12 2015-04-08          3717  SUMNER    50674  Bremer  1011200.0   
13 2015-01-14          3717  SUMNER    50674  Bremer  1081390.0   
14 2015-01-07          3717  SUMNER    50674  Bremer  1062310.0   
15 2015-11-23          3717  SUMNER    50674  Bremer  1031200.0   
16 2015-06-10          3717  SUMNER    50674  Bremer  1031200.0   
17 2015-08-05          3717  SUMNER    50674  Bremer  1031080.0   
18 2015-10-28          3717  SUMNER    50674  Bremer  1062310.0   
19 2015-11-04          3717  SUMNER    50674  Bremer  1051110.0   
20 2015-09-16          3717  SUMNER    50674  Bremer  1012200.0   
21 2015-09-16          3717  SUMNER    50674  Bremer  1081900.0   
22 2015-01-21          3717  SUMNER    50674  Bremer  1062300.0   
23 2015-10-28          3717  SUMNER    50674  Bremer  1081390.0   
24 2015-02-04          3717  SUMNER    50674  Bremer  1012100.0   
25 2015-03-04          3717  SUMNER    50674  Bremer  1051110.0   
26 2015-03-25          3717  SUMNER    50674  Bremer  1062310.0   
27 2015-04-01          3717  SUMNER    50674  Bremer  1012100.0   
28 2015-12-16          3717  SUMNER    50674  Bremer  1081030.0   
29 2015-05-13          3717  SUMNER    50674  Bremer  1022100.0   
30 2015-05-27          3717  SUMNER    50674  Bremer  1032080.0   
31 2015-07-22          3717  SUMNER    50674  Bremer  1031080.0   
32 2015-07-15          3717  SUMNER    50674  Bremer  1012200.0   
33 2015-05-06          3717  SUMNER    50674  Bremer  1012100.0   
34 2015-07-15          3717  SUMNER    50674  Bremer  1051100.0   
35 2015-12-29          3717  SUMNER    50674  Bremer  1032080.0   
36 2015-09-30          3717  SUMNER    50674  Bremer  1062300.0   
37 2015-04-29          3717  SUMNER    50674  Bremer  1012100.0   
38 2015-06-03          3717  SUMNER    50674  Bremer  1062300.0   
39 2015-09-02          3717  SUMNER    50674  Bremer  1081335.0   
40 2015-10-14          3717  SUMNER    50674  Bremer  1011100.0   
41 2015-04-01          3717  SUMNER    50674  Bremer  1011100.0   
42 2015-05-13          3717  SUMNER    50674  Bremer  1031080.0   
43 2015-08-05          3717  SUMNER    50674  Bremer  1062310.0   
44 2015-10-07          3717  SUMNER    50674  Bremer  1012100.0   
45 2015-11-11          3717  SUMNER    50674  Bremer  1081305.0   
46 2015-10-28          3717  SUMNER    50674  Bremer  1062300.0   
47 2015-07-15          3717  SUMNER    50674  Bremer  1062300.0   
48 2015-09-02          3717  SUMNER    50674  Bremer  1032200.0   
49 2015-03-11          3717  SUMNER    50674  Bremer  1012100.0   

                         Category Name  Item Number  \
0                     APRICOT BRANDIES        54436   
1                     APRICOT BRANDIES        54436   
2   MISC. AMERICAN CORDIALS & LIQUEURS        75211   
3                    CANADIAN WHISKIES        11777   
4            STRAIGHT BOURBON WHISKIES        19476   
5                       IRISH WHISKIES        15621   
6                         FLAVORED RUM        44520   
7                    CANADIAN WHISKIES        11296   
8                       CREAM LIQUEURS        80482   
9                       VODKA FLAVORED   

In [32]:
Iowa2015new.sort(['Store Number'],ascending=[True])

C:\Users\abhaindurkar\Anaconda3\New folder\envs\econ\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


Date  Store Number         City Zip Code      County   Category  \
153267 2015-12-23          2106  CEDAR FALLS    50613  Black Hawk  1011100.0   
153170 2015-05-07          2106  CEDAR FALLS    50613  Black Hawk  1081900.0   
153171 2015-04-02          2106  CEDAR FALLS    50613  Black Hawk  1012100.0   
153172 2015-07-30          2106  CEDAR FALLS    50613  Black Hawk  1081200.0   
153173 2015-01-22          2106  CEDAR FALLS    50613  Black Hawk  1012100.0   
153174 2015-09-03          2106  CEDAR FALLS    50613  Black Hawk  1081900.0   
153175 2015-10-29          2106  CEDAR FALLS    50613  Black Hawk  1022100.0   
153176 2015-07-16          2106  CEDAR FALLS    50613  Black Hawk  1081330.0   
153177 2015-06-18          2106  CEDAR FALLS    50613  Black Hawk  1012210.0   
153178 2015-01-22          2106  CEDAR FALLS    50613  Black Hawk  1081390.0   
153179 2015-11-05          2106  CEDAR FALLS    50613  Black Hawk  1032080.0   
153180 2015-02-19          2106  CEDAR FALLS    50613  Black Hawk  1012210.0   
153181 2015-04-30          2106  CEDAR FALLS    50613  Black Hawk  1032200.0   
153182 2015-11-19          2106  CEDAR FALLS    50613  Black Hawk  1022100.0   
153183 2015-11-05          2106  CEDAR FALLS    50613  Black Hawk  1041100.0   
153184 2015-04-30          2106  CEDAR FALLS    50613  Black Hawk  1032200.0   
153185 2015-04-16          2106  CEDAR FALLS    50613  Black Hawk  1032080.0   
153186 2015-08-27          2106  CEDAR FALLS    50613  Black Hawk  1041100.0   
153187 2015-08-27          2106  CEDAR FALLS    50613  Black Hawk  1011200.0   
153188 2015-11-05          2106  CEDAR FALLS    50613  Black Hawk  1032200.0   
153189 2015-04-02          2106  CEDAR FALLS    50613  Black Hawk  1011100.0   
153190 2015-05-28          2106  CEDAR FALLS    50613  Black Hawk  1041100.0   
153191 2015-12-03          2106  CEDAR FALLS    50613  Black Hawk  1031200.0   
153192 2015-05-28          2106  CEDAR FALLS    50613  Black Hawk  1062300.0   
153193 2015-09-03          2106  CEDAR FALLS    50613  Black Hawk  1031080.0   
153194 2015-09-17          2106  CEDAR FALLS    50613  Black Hawk  1081700.0   
153195 2015-05-07          2106  CEDAR FALLS    50613  Black Hawk  1031080.0   
153196 2015-12-30          2106  CEDAR FALLS    50613  Black Hawk  1032100.0   
153197 2015-09-10          2106  CEDAR FALLS    50613  Black Hawk  1032080.0   
153198 2015-07-01          2106  CEDAR FALLS    50613  Black Hawk  1032080.0   
...           ...           ...          ...      ...         ...        ...   
191502 2015-12-10          9002     LECLAIRE    52753       Scott  1031080.0   
191533 2015-07-16          9002     LECLAIRE    52753       Scott  1041100.0   
191532 2015-01-22          9002     LECLAIRE    52753       Scott  1041100.0   
191531 2015-07-01          9002     LECLAIRE    52753       Scott  1011100.0   
191530 2015-04-30          9002     LECLAIRE    52753       Scott  1011500.0   
191529 2015-11-05          9002     LECLAIRE    52753       Scott  1011100.0   
191528 2015-06-18          9002     LECLAIRE    52753       Scott  1031080.0   
191527 2015-10-01          9002     LECLAIRE    52753       Scott  1011500.0   
191534 2015-09-17          9002     LECLAIRE    52753       Scott  1011100.0   
216375 2015-02-09          9010      NORWALK    50211      Warren  1081900.0   
216377 2015-05-20          9010      NORWALK    50211      Warren  1081600.0   
216376 2015-03-31          9010      NORWALK    50211      Warren  1011100.0   
216373 2015-02-09          9010      NORWALK    50211      Warren  1011100.0   
216378 2015-04-23          9010      NORWALK    50211      Warren  1011100.0   
216372 2015-08-06          9010      NORWALK    50211      Warren  1081900.0   
216371 2015-09-17          9010      NORWALK    50211      Warren  1081900.0   
216374 2015-06-16          9010      NORWALK    50211      Warren  1011100.0   
216379 2015-02-09          9010      NORWALK    50211      Warren  1051010.0   
216370 2015-0

In [33]:
Iowa2015new[Iowa2015new["salesdummy"]<12].count()["Store Number"]

21644

In [34]:
Iowa2015new['Store Number'].count()

218594

Here , we see that the total number of stores which have the data are 218594 and the stores for which we do not have data are only 21644, to decide whether this part of the data set is important, I calcultee the percentage of the stores that have less than one year data which is (21644/218594)100= 9%. So considering that there are other stores in 2016 which are not the part of this data frame the percentage of these stores would be even less than 9%. Hence I feel safe to assume that it will not affect the analysis If I drop these stores.

In [35]:
Iowa2015fresh= Iowa2015new[Iowa2015new["salesdummy"]==12]

Iowa2015fresh.head()

Date  Store Number    City Zip Code  County   Category  \
0 2015-11-04          3717  SUMNER    50674  Bremer  1051100.0   
1 2015-06-10          3717  SUMNER    50674  Bremer  1051100.0   
2 2015-01-21          3717  SUMNER    50674  Bremer  1081900.0   
3 2015-11-11          3717  SUMNER    50674  Bremer  1012100.0   
4 2015-01-07          3717  SUMNER    50674  Bremer  1011200.0   

                        Category Name  Item Number           Item Description  \
0                    APRICOT BRANDIES        54436  Mr. Boston Apricot Brandy   
1                    APRICOT BRANDIES        54436  Mr. Boston Apricot Brandy   
2  MISC. AMERICAN CORDIALS & LIQUEURS        75211              Kinky Liqueur   
3                   CANADIAN WHISKIES        11777               Black Velvet   
4           STRAIGHT BOURBON WHISKIES        19476               Maker's Mark   

   Bottle Volume (ml)  State Bottle Cost  State Bottle Retail  Bottles Sold  \
0                 750               4.50                 6.75            12   
1                 750               4.50                 6.75             4   
2                 750              10.00                15.00             2   
3                1000               6.63                 9.95             2   
4                 750              16.79                25.19             1   

   Sale (Dollars)  Volume Sold (Liters)  Volume Sold (Gallons)  Month  Year  \
0           81.00                  9.00                   2.38     11  2015   
1           27.00                  3.00                   0.79      6  2015   
2           30.00                  1.50                   0.40      1  2015   
3           19.90                  2.00                   0.53     11  2015   
4           25.19                  0.75                   0.20      1  2015   

   salesdummy  
0        12.0  
1        12.0  
2        12.0  
3        12.0  
4        12.0

In [36]:
Iowa2015fresh['Store Number'].count()

196950


## 5. Case 1 - Proposals for new tax rates 

---

You are an economist working for the Iowa State tax board. The Iowa State legislature is considering changes in the liquor tax rates and has assigned you to the project.

### 5.1 Calculate yearly liquor sales for each store in 2015.

In [37]:
Iowa2015yearlysales = Iowa2015fresh.groupby(['Store Number',])['Sale (Dollars)'].sum().reset_index()
Iowa2015yearlysales.head()

Store Number  Sale (Dollars)
0          2106       146326.22
1          2113         9310.22
2          2130       111871.43
3          2152         7721.08
4          2178        24324.18

The Sale(Dollars) column represents the sum of monthly sales for each store which in this case is the yearly sales of ech store of 2015.

### 5.2 Calculate the profit each store is making in 2015.


In [68]:
Iowa2015fresh = Iowa2015fresh.rename(index=str, columns={ "Sale (Dollars)": "Sale_Dollars", "State Bottle Cost": "State_Bottle_Cost", "State Bottle Retail": "State_Bottle_Retail", "Bottles Sold": "Bottles_Sold"})

In [69]:
Iowa2015fresh['Month_dummy']= Iowa2015fresh['salesdummy']
Iowa2015fresh.loc[Iowa2015fresh.Month_dummy == 12, 'Month_dummy']=1
Iowa2015fresh

Date  Store Number        City Zip Code   County   Category  \
0      2015-11-04          3717      SUMNER    50674   Bremer  1051100.0   
1      2015-06-10          3717      SUMNER    50674   Bremer  1051100.0   
2      2015-01-21          3717      SUMNER    50674   Bremer  1081900.0   
3      2015-11-11          3717      SUMNER    50674   Bremer  1012100.0   
4      2015-01-07          3717      SUMNER    50674   Bremer  1011200.0   
5      2015-02-18          3717      SUMNER    50674   Bremer  1012300.0   
6      2015-08-19          3717      SUMNER    50674   Bremer  1062300.0   
7      2015-12-09          3717      SUMNER    50674   Bremer  1012100.0   
8      2015-02-04          3717      SUMNER    50674   Bremer  1081200.0   
9      2015-12-22          3717      SUMNER    50674   Bremer  1031200.0   
10     2015-04-29          3717      SUMNER    50674   Bremer  1012100.0   
11     2015-10-28          3717      SUMNER    50674   Bremer  1081370.0   
12     2015-04-08          3717      SUMNER    50674   Bremer  1011200.0   
13     2015-01-14          3717      SUMNER    50674   Bremer  1081390.0   
14     2015-01-07          3717      SUMNER    50674   Bremer  1062310.0   
15     2015-11-23          3717      SUMNER    50674   Bremer  1031200.0   
16     2015-06-10          3717      SUMNER    50674   Bremer  1031200.0   
17     2015-08-05          3717      SUMNER    50674   Bremer  1031080.0   
18     2015-10-28          3717      SUMNER    50674   Bremer  1062310.0   
19     2015-11-04          3717      SUMNER    50674   Bremer  1051110.0   
20     2015-09-16          3717      SUMNER    50674   Bremer  1012200.0   
21     2015-09-16          3717      SUMNER    50674   Bremer  1081900.0   
22     2015-01-21          3717      SUMNER    50674   Bremer  1062300.0   
23     2015-10-28          3717      SUMNER    50674   Bremer  1081390.0   
24     2015-02-04          3717      SUMNER    50674   Bremer  1012100.0   
25     2015-03-04          3717      SUMNER    50674   Bremer  1051110.0   
26     2015-03-25          3717      SUMNER    50674   Bremer  1062310.0   
27     2015-04-01          3717      SUMNER    50674   Bremer  1012100.0   
28     2015-12-16          3717      SUMNER    50674   Bremer  1081030.0   
29     2015-05-13          3717      SUMNER    50674   Bremer  1022100.0   
...           ...           ...         ...      ...      ...        ...   
217646 2015-02-05          4974  DES MOINES    50317     Polk  1031100.0   
217647 2015-05-07          4974  DES MOINES    50317     Polk  1032080.0   
218299 2015-06-02          4702  FORT DODGE    50501  Webster  1012100.0   
218300 2015-12-01          4702  FORT DODGE    50501  Webster  1031080.0   
218301 2015-01-13          4702  FORT DODGE    50501  Webster  1062310.0   
218302 2015-12-15          4702  FORT DODGE    50501  Webster  1081600.0   
218303 2015-10-20          4702  FORT DODGE    50501  Webster  1031080.0   
218304 2015-12-15          4702  FORT DODGE    50501  Webster  1701100.0   
218305 2015-07-28          4702  FORT DODGE    50501  Webster  1052010.0   
218306 2015-11-03          4702  FORT DODGE    50501  Webster  1011100.0   
218307 2015-01-13          4702  FORT DODGE    50501  Webster  1062200.0   
218308 2015-11-03          4702  FORT DODGE    50501  Webster  1062200.0   
218309 2015-05-05          4702  FORT DODGE    50501  Webster  1022100.0   
218310 2015-08-18          4702  FORT DODGE    50501  Webster  1081200.0   
218311 2015-02-10          4702  FORT DODGE    50501  Webster  1011200.0   
218312 2015-09-01          4702  FORT DODGE    50501  Webster  1062300.0   
218313 2015-10-20          4702  FORT DODGE    50501  Webster  1032080.0   
218314 2015-04-14          4702  FORT DODGE    50501  Webster  1032080.0   
218315 2015-07-14          4702  FORT DODGE    50501  Webster  1012100.0   
218316 2015-08-18          4702  FORT DODGE    50501  Webster  1062200.0   
218317 2015-12-08          4702  FORT DODGE    50501  Webster

In [70]:
yearlysale=Iowa2015fresh.groupby(['Store Number','Month_dummy'])['Sale_Dollars'].sum().reset_index()
yearlysale.head()


Store Number  Month_dummy  Sale_Dollars
0          2106          1.0     146326.22
1          2113          1.0       9310.22
2          2130          1.0     111871.43
3          2152          1.0       7721.08
4          2178          1.0      24324.18

In [71]:
Iowa2015fresh['Cost']=(Iowa2015fresh.Bottles_Sold) * (Iowa2015fresh.State_Bottle_Cost)
yearlycost=Iowa2015fresh.groupby(['Store Number','Month_dummy'])['Cost'].sum().reset_index()
yearlycost.head(5)

Store Number  Month_dummy      Cost
0          2106          1.0  97488.14
1          2113          1.0   6201.18
2          2130          1.0  74546.23
3          2152          1.0   5133.55
4          2178          1.0  16158.48

In [72]:
Iowa2015profit=pd.merge(yearlysale, yearlycost, on=['Store Number','Month_dummy'], how='left')
Iowa2015profit.head(5)

Store Number  Month_dummy  Sale_Dollars      Cost
0          2106          1.0     146326.22  97488.14
1          2113          1.0       9310.22   6201.18
2          2130          1.0     111871.43  74546.23
3          2152          1.0       7721.08   5133.55
4          2178          1.0      24324.18  16158.48

In [73]:
Iowa2015profit['Profit']=Iowa2015profit.Sale_Dollars - Iowa2015profit.Cost
Iowa2015profit.head(5)

Store Number  Month_dummy  Sale_Dollars      Cost    Profit
0          2106          1.0     146326.22  97488.14  48838.08
1          2113          1.0       9310.22   6201.18   3109.04
2          2130          1.0     111871.43  74546.23  37325.20
3          2152          1.0       7721.08   5133.55   2587.53
4          2178          1.0      24324.18  16158.48   8165.70

These are the yearly profit incurred by each store in 2015 (This calculation however, assumes that the selling price of each bottle is equal to the dollar sale which is according to the website the amount store paid, and cost price of each bottle is the cost paid by alchoholic breverages devision for each bottle multiplied by the number of bottles, this assumption is required as the data according to the website has no data of information on how many bottles the store sells, it only gives how many bottles the store ordered)

### 5.3 Investigate which Iowa counties are making the most profit on liquor per gallon in 2015.

In [74]:
Iowa2015fresh = Iowa2015fresh.rename(index=str, columns={ "Volume Sold (Gallons)": "VolumeSold_gallons"})

In [75]:
Iowa2015fresh_county=Iowa2015fresh.groupby(['County'])['Month'].nunique().reset_index()

In [76]:
# Create a month dummy if county has 12-month data = 1
Iowa2015fresh_county['month_dummy']= Iowa2015fresh_county['Month']
Iowa2015fresh_county.loc[Iowa2015fresh_county.month_dummy == 12, 'month_dummy']=1

In [77]:
Iowa2015county=pd.merge(Iowa2015fresh_county, Iowa2015fresh, on=['County'], how='left')


In [78]:
Iowa2015county.head(4)

County  Month_x  month_dummy       Date  Store Number    City Zip Code  \
0  Adair       12            1 2015-10-26          3461  STUART    50250   
1  Adair       12            1 2015-03-23          3461  STUART    50250   
2  Adair       12            1 2015-09-04          3461  STUART    50250   
3  Adair       12            1 2015-04-13          3461  STUART    50250   

    Category              Category Name  Item Number  ...    \
0  1012100.0          CANADIAN WHISKIES        12408  ...     
1  1031080.0             VODKA 80 PROOF        36307  ...     
2  1011200.0  STRAIGHT BOURBON WHISKIES        16516  ...     
3  1081330.0             PEACH SCHNAPPS        82846  ...     

  State_Bottle_Retail  Bottles_Sold  Sale_Dollars  Volume Sold (Liters)  \
0               12.51             6         75.06                 10.50   
1                6.08            12         72.96                 12.00   
2                9.24             3         27.72                  2.25   
3                9.45             3         28.35                  2.25   

   VolumeSold_gallons  Month_y  Year  salesdummy  Month_dummy   Cost  
0                2.77       10  2015        12.0          1.0  47.64  
1                3.17        3  2015        12.0          1.0  48.60  
2                0.59        9  2015        12.0          1.0  18.48  
3                0.59        4  2015        12.0          1.0  18.90  

[4 rows x 23 columns]

In [79]:
Iowa2015county['Costgallon']= (Iowa2015county.Bottles_Sold) * (Iowa2015county.State_Bottle_Cost)

In [80]:
a=Iowa2015county.groupby(['County','month_dummy'])['Sale_Dollars', 'Costgallon', 'VolumeSold_gallons'].sum().reset_index()
a['Profitgalloncounty']=(a.Sale_Dollars-a.Costgallon)/a.VolumeSold_gallons

a[0:3]

County  month_dummy  Sale_Dollars  Costgallon  VolumeSold_gallons  \
0      Adair            1      35084.90    23364.19              770.24   
1      Adams            1      10245.14     6827.47              216.98   
2  Allamakee            1      73773.43    49058.10             1530.57   

   Profitgalloncounty  
0           15.216958  
1           15.751083  
2           16.147795

This is the profit of each store per  gallon in 2015.

### 5.4  Does profit scale proportionally to store size?

Size of a store can be defined as the total gallons sold in 2015. Is the profit to store size ratio increasing as store size increases? Decreasing? Consistent?

In [81]:
Iowamerged=pd.merge(Iowa2015profit,Iowa2015fresh, on=['Store Number','Month_dummy'], how='left')
Iowamerged.head(5)

Store Number  Month_dummy  Sale_Dollars_x    Cost_x    Profit       Date  \
0          2106          1.0       146326.22  97488.14  48838.08 2015-08-20   
1          2106          1.0       146326.22  97488.14  48838.08 2015-03-12   
2          2106          1.0       146326.22  97488.14  48838.08 2015-07-30   
3          2106          1.0       146326.22  97488.14  48838.08 2015-01-22   
4          2106          1.0       146326.22  97488.14  48838.08 2015-08-13   

          City Zip Code      County   Category   ...   State_Bottle_Cost  \
0  CEDAR FALLS    50613  Black Hawk  1032080.0   ...               14.99   
1  CEDAR FALLS    50613  Black Hawk  1011200.0   ...               21.02   
2  CEDAR FALLS    50613  Black Hawk  1081390.0   ...               15.75   
3  CEDAR FALLS    50613  Black Hawk  1041100.0   ...                4.23   
4  CEDAR FALLS    50613  Black Hawk  1081317.0   ...                7.62   

   State_Bottle_Retail Bottles_Sold  Sale_Dollars_y  Volume Sold (Liters)  \
0                22.49           36          809.64                  36.0   
1                31.53            6          189.18                   4.5   
2                23.63           12          283.56                  12.0   
3                 6.35           12           76.20                  12.0   
4                11.43           12          137.16                  12.0   

   VolumeSold_gallons  Month  Year  salesdummy  Cost_y  
0                9.51      8  2015        12.0  539.64  
1                1.19      3  2015        12.0  126.12  
2                3.17      7  2015        12.0  189.00  
3                3.17      1  2015        12.0   50.76  
4                3.17      8  2015        12.0   91.44  

[5 rows x 24 columns]

In [82]:
Iowamerged['Iowa2015ratio']=Iowamerged.Profit/Iowamerged.VolumeSold_gallons
Iowamerged.head()

Store Number  Month_dummy  Sale_Dollars_x    Cost_x    Profit       Date  \
0          2106          1.0       146326.22  97488.14  48838.08 2015-08-20   
1          2106          1.0       146326.22  97488.14  48838.08 2015-03-12   
2          2106          1.0       146326.22  97488.14  48838.08 2015-07-30   
3          2106          1.0       146326.22  97488.14  48838.08 2015-01-22   
4          2106          1.0       146326.22  97488.14  48838.08 2015-08-13   

          City Zip Code      County   Category      ...        \
0  CEDAR FALLS    50613  Black Hawk  1032080.0      ...         
1  CEDAR FALLS    50613  Black Hawk  1011200.0      ...         
2  CEDAR FALLS    50613  Black Hawk  1081390.0      ...         
3  CEDAR FALLS    50613  Black Hawk  1041100.0      ...         
4  CEDAR FALLS    50613  Black Hawk  1081317.0      ...         

  State_Bottle_Retail  Bottles_Sold Sale_Dollars_y  Volume Sold (Liters)  \
0               22.49            36         809.64                  36.0   
1               31.53             6         189.18                   4.5   
2               23.63            12         283.56                  12.0   
3                6.35            12          76.20                  12.0   
4               11.43            12         137.16                  12.0   

   VolumeSold_gallons  Month  Year  salesdummy  Cost_y  Iowa2015ratio  
0                9.51      8  2015        12.0  539.64    5135.444795  
1                1.19      3  2015        12.0  126.12   41040.403361  
2                3.17      7  2015        12.0  189.00   15406.334385  
3                3.17      1  2015        12.0   50.76   15406.334385  
4                3.17      8  2015        12.0   91.44   15406.334385  

[5 rows x 25 columns]

This is profit to store size ratio

In [83]:
Relationship=Iowamerged.groupby(['Iowa2015ratio'])['VolumeSold_gallons'].sum().reset_index()

Relationship.head()

Iowa2015ratio  VolumeSold_gallons
0      21.205494              277.38
1      21.689740              277.38
2      22.366357              138.69
3      25.634797              138.69
4      26.915747              277.38

The profitto storesize ratio is neither increasing nor decreasing with store size it is mostly consistent

### 5.5 Create a broader category for liquor type.

Liquor types are pretty granular in this dataset. Create a column that categorizes these types into a smaller amount of categories. The categories you decide on are up to you.

In [84]:
Iowamerged.head()

Store Number  Month_dummy  Sale_Dollars_x    Cost_x    Profit       Date  \
0          2106          1.0       146326.22  97488.14  48838.08 2015-08-20   
1          2106          1.0       146326.22  97488.14  48838.08 2015-03-12   
2          2106          1.0       146326.22  97488.14  48838.08 2015-07-30   
3          2106          1.0       146326.22  97488.14  48838.08 2015-01-22   
4          2106          1.0       146326.22  97488.14  48838.08 2015-08-13   

          City Zip Code      County   Category      ...        \
0  CEDAR FALLS    50613  Black Hawk  1032080.0      ...         
1  CEDAR FALLS    50613  Black Hawk  1011200.0      ...         
2  CEDAR FALLS    50613  Black Hawk  1081390.0      ...         
3  CEDAR FALLS    50613  Black Hawk  1041100.0      ...         
4  CEDAR FALLS    50613  Black Hawk  1081317.0      ...         

  State_Bottle_Retail  Bottles_Sold Sale_Dollars_y  Volume Sold (Liters)  \
0               22.49            36         809.64                  36.0   
1               31.53             6         189.18                   4.5   
2               23.63            12         283.56                  12.0   
3                6.35            12          76.20                  12.0   
4               11.43            12         137.16                  12.0   

   VolumeSold_gallons  Month  Year  salesdummy  Cost_y  Iowa2015ratio  
0                9.51      8  2015        12.0  539.64    5135.444795  
1                1.19      3  2015        12.0  126.12   41040.403361  
2                3.17      7  2015        12.0  189.00   15406.334385  
3                3.17      1  2015        12.0   50.76   15406.334385  
4                3.17      8  2015        12.0   91.44   15406.334385  

[5 rows x 25 columns]

In [85]:
list(set(Iowamerged['Category Name']))


['SCOTCH WHISKIES',
 nan,
 'STRAWBERRY SCHNAPPS',
 'ROCK & RYE',
 'CHERRY BRANDIES',
 'OTHER PROOF VODKA',
 'AMERICAN DRY GINS',
 'CANADIAN WHISKIES',
 'BLACKBERRY BRANDIES',
 'IMPORTED VODKA - MISC',
 'LOW PROOF VODKA',
 'IRISH WHISKIES',
 'IMPORTED AMARETTO',
 'ANISETTE',
 'BOTTLED IN BOND BOURBON',
 'PEPPERMINT SCHNAPPS',
 'IMPORTED GRAPE BRANDIES',
 'BARBADOS RUM',
 'TENNESSEE WHISKIES',
 'IMPORTED DRY GINS',
 'SPICED RUM',
 'SINGLE BARREL BOURBON WHISKIES',
 'SINGLE MALT SCOTCH',
 'AMARETTO - IMPORTED',
 'CORN WHISKIES',
 'APRICOT BRANDIES',
 'TEQUILA',
 'FLAVORED RUM',
 'JAMAICA RUM',
 'COFFEE LIQUEURS',
 'MISCELLANEOUS SCHNAPPS',
 'MISC. IMPORTED CORDIALS & LIQUEURS',
 'MISC. AMERICAN CORDIALS & LIQUEURS',
 'VODKA FLAVORED',
 'STRAIGHT RYE WHISKIES',
 'RASPBERRY SCHNAPPS',
 'DARK CREME DE CACAO',
 'VODKA 80 PROOF',
 'PEACH SCHNAPPS',
 'TROPICAL FRUIT SCHNAPPS',
 'AMERICAN GRAPE BRANDIES',
 'TRIPLE SEC',
 'WATERMELON SCHNAPPS',
 'IMPORTED SCHNAPPS',
 'AMERICAN SLOE GINS',
 'DISTI

In [86]:
Iowamerged['category_liquor'] = np.where(Iowamerged['Category Name'].str.contains('WHISKIES'), "Whisky",
       np.where(Iowamerged['Category Name'].str.contains('BRANDIES') , "Brandy",
       np.where(Iowamerged['Category Name'].str.contains('SCHNAPPS'), "Schnapps",  
       np.where(Iowamerged['Category Name'].str.contains('RUM'), "Rum",         
       np.where(Iowamerged['Category Name'].str.contains('VODKA'), "Vodka", "Other" )))))

Iowamerged['category_liquor'].head()

Iowamerged.groupby(['category_liquor']).count()['Category'].reset_index()

category_liquor  Category
0          Brandy     10712
1           Other     50155
2             Rum     23827
3        Schnapps     10723
4           Vodka     50247
5          Whisky     51222

### 5.6 Do relationships exist between the broader liquor type and profit?

In [87]:
profit_relation= Iowamerged.groupby(['category_liquor']).mean()["Profit"].reset_index()


In [88]:
Iowamerged.head()


Store Number  Month_dummy  Sale_Dollars_x    Cost_x    Profit       Date  \
0          2106          1.0       146326.22  97488.14  48838.08 2015-08-20   
1          2106          1.0       146326.22  97488.14  48838.08 2015-03-12   
2          2106          1.0       146326.22  97488.14  48838.08 2015-07-30   
3          2106          1.0       146326.22  97488.14  48838.08 2015-01-22   
4          2106          1.0       146326.22  97488.14  48838.08 2015-08-13   

          City Zip Code      County   Category       ...        Bottles_Sold  \
0  CEDAR FALLS    50613  Black Hawk  1032080.0       ...                  36   
1  CEDAR FALLS    50613  Black Hawk  1011200.0       ...                   6   
2  CEDAR FALLS    50613  Black Hawk  1081390.0       ...                  12   
3  CEDAR FALLS    50613  Black Hawk  1041100.0       ...                  12   
4  CEDAR FALLS    50613  Black Hawk  1081317.0       ...                  12   

   Sale_Dollars_y Volume Sold (Liters)  VolumeSold_gallons  Month  Year  \
0          809.64                 36.0                9.51      8  2015   
1          189.18                  4.5                1.19      3  2015   
2          283.56                 12.0                3.17      7  2015   
3           76.20                 12.0                3.17      1  2015   
4          137.16                 12.0                3.17      8  2015   

   salesdummy  Cost_y  Iowa2015ratio  category_liquor  
0        12.0  539.64    5135.444795            Vodka  
1        12.0  126.12   41040.403361           Whisky  
2        12.0  189.00   15406.334385         Schnapps  
3        12.0   50.76   15406.334385            Other  
4        12.0   91.44   15406.334385         Schnapps  

[5 rows x 26 columns]

In [89]:
Iowamerged2= pd.merge(Iowamerged,profit_relation , on=['category_liquor'], how='right')

Iowamerged2.head()


Store Number  Month_dummy  Sale_Dollars_x    Cost_x  Profit_x       Date  \
0          2106          1.0       146326.22  97488.14  48838.08 2015-08-20   
1          2106          1.0       146326.22  97488.14  48838.08 2015-04-16   
2          2106          1.0       146326.22  97488.14  48838.08 2015-07-16   
3          2106          1.0       146326.22  97488.14  48838.08 2015-04-09   
4          2106          1.0       146326.22  97488.14  48838.08 2015-11-19   

          City Zip Code      County   Category      ...      Sale_Dollars_y  \
0  CEDAR FALLS    50613  Black Hawk  1032080.0      ...              809.64   
1  CEDAR FALLS    50613  Black Hawk  1031080.0      ...              166.56   
2  CEDAR FALLS    50613  Black Hawk  1032200.0      ...               29.88   
3  CEDAR FALLS    50613  Black Hawk  1031200.0      ...               21.00   
4  CEDAR FALLS    50613  Black Hawk  1031200.0      ...               40.32   

   Volume Sold (Liters) VolumeSold_gallons  Month  Year  salesdummy  Cost_y  \
0                  36.0               9.51      8  2015        12.0  539.64   
1                  12.0               3.17      4  2015        12.0  111.00   
2                   1.5               0.40      7  2015        12.0   19.92   
3                   1.5               0.40      4  2015        12.0   14.00   
4                   4.5               1.19     11  2015        12.0   26.88   

   Iowa2015ratio  category_liquor      Profit_y  
0    5135.444795            Vodka  25812.758887  
1   15406.334385            Vodka  25812.758887  
2  122095.200000            Vodka  25812.758887  
3  122095.200000            Vodka  25812.758887  
4   41040.403361            Vodka  25812.758887  

[5 rows x 27 columns]

In [90]:
Profit_new = Iowamerged.groupby(['category_liquor']).sum()["Profit"].reset_index()
Profit_new.rename(columns={'YearlyProfit':'Profit_new'}, inplace=True)


In [91]:
Iowa_new= pd.merge(Iowamerged2, Profit_new, on=['category_liquor'], how='right')



In [92]:
Per_Gallons = Iowa_new.groupby(['category_liquor']).sum()[['VolumeSold_gallons']]




In [93]:
Iowa_new.reset_index(level=['Profit_new', 'profit_relation'])




index  Store Number  Month_dummy  Sale_Dollars_x    Cost_x  Profit_x  \
0            0          2106          1.0       146326.22  97488.14  48838.08   
1            1          2106          1.0       146326.22  97488.14  48838.08   
2            2          2106          1.0       146326.22  97488.14  48838.08   
3            3          2106          1.0       146326.22  97488.14  48838.08   
4            4          2106          1.0       146326.22  97488.14  48838.08   
5            5          2106          1.0       146326.22  97488.14  48838.08   
6            6          2106          1.0       146326.22  97488.14  48838.08   
7            7          2106          1.0       146326.22  97488.14  48838.08   
8            8          2106          1.0       146326.22  97488.14  48838.08   
9            9          2106          1.0       146326.22  97488.14  48838.08   
10          10          2106          1.0       146326.22  97488.14  48838.08   
11          11          2106          1.0       146326.22  97488.14  48838.08   
12          12          2106          1.0       146326.22  97488.14  48838.08   
13          13          2106          1.0       146326.22  97488.14  48838.08   
14          14          2106          1.0       146326.22  97488.14  48838.08   
15          15          2106          1.0       146326.22  97488.14  48838.08   
16          16          2106          1.0       146326.22  97488.14  48838.08   
17          17          2106          1.0       146326.22  97488.14  48838.08   
18          18          2106          1.0       146326.22  97488.14  48838.08   
19          19          2106          1.0       146326.22  97488.14  48838.08   
20          20          2106          1.0       146326.22  97488.14  48838.08   
21          21          2106          1.0       146326.22  97488.14  48838.08   
22          22          2106          1.0       146326.22  97488.14  48838.08   
23          23          2106          1.0       146326.22  97488.14  48838.08   
24          24          2106          1.0       146326.22  97488.14  48838.08   
25          25          2106          1.0       146326.22  97488.14  48838.08   
26          26          2106          1.0       146326.22  97488.14  48838.08   
27          27          2106          1.0       146326.22  97488.14  48838.08   
28          28          2106          1.0       146326.22  97488.14  48838.08   
29          29          2106          1.0       146326.22  97488.14  48838.08   
...        ...           ...          ...             ...       ...       ...   
196920  196920          5080          1.0        23506.93  15661.68   7845.25   
196921  196921          5080          1.0        23506.93  15661.68   7845.25   
196922  196922          5080          1.0        23506.93  15661.68   7845.25   
196923  196923          5080          1.0        23506.93  15661.68   7845.25   
196924  196924          5080          1.0        23506.93  15661.68   7845.25   
196925  196925          5080          1.0        23506.93  15661.68   7845.25   
196926  196926          5080          1.0        23506.93  15661.68   7845.25   
196927  196927          5080          1.0        23506.93  15661.68   7845.25   
196928  196928          5080          1.0        23506.93  15661.68   7845.25   
196929  196929          5080          1.0        23506.93  15661.68   7845.25   
196930  196930          5080          1.0        23506.93  15661.68   7845.25   
196931  196931          5080          1.0        23506.93  15661.68   7845.25   
196932  196932          5080          1.0        23506.93  15661.68   7845.25   
196933  196933          5086          1.0         6410.35   4269.42   2140.93   
196934  196934          5086          1.0         6410.35   4269.42   2140.93   
196935  196935          5086          1.0         6410.35   4269.42   2140.93   
196936  196936          5086          1.0         6410.35   4269.42   2140.93   
196937  196937          5089          1.

In [94]:
Per_Gallons_Profit = Iowa_new.groupby(['category_liquor']).mean()[['Profit','VolumeSold_gallons']]
Per_Gallons_Profit.sort(['Profit'], ascending=1, inplace=True)
Per_Gallons_Profit

C:\Users\abhaindurkar\Anaconda3\New folder\envs\econ\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


Profit  VolumeSold_gallons
category_liquor                                  
Brandy           2.217466e+08            1.327792
Schnapps         3.210366e+08            1.765658
Rum              6.041776e+08            2.769953
Whisky           1.214036e+09            2.531439
Vodka            1.297014e+09            2.856504
Other            1.563014e+09            2.088064

In this table we can see that magnitude of the relation of liquor type Brandy with profit is highest, followed by Whisky, then Rum and Vodka are nearly equal.


### 5.7 Are there any noticeable relationships between liquor brand and sales? Profit?

In [95]:
Per_Gallons_Sales = Iowamerged2.groupby(['category_liquor']).mean()[['Profit_x','Sale_Dollars_x']]
Per_Gallons_Sales.sort(['Profit_x'], ascending=1, inplace=True)
Per_Gallons_Sales

C:\Users\abhaindurkar\Anaconda3\New folder\envs\econ\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


Profit_x  Sale_Dollars_x
category_liquor                              
Brandy           20700.766353    61944.553530
Whisky           23671.874430    70831.261489
Rum              25356.845329    75881.416470
Vodka            25812.758887    77251.017263
Schnapps         29939.061019    89615.821065
Other            31163.662764    93277.244581

We can see that profit is increasing as the sales are increasing and it is highest for other followed by Schnapps.

### 5.8 The tax board wants to design a tax or taxes that affect larger stores more than smaller "mom and pop" stores.

Based on your investigations into the data, come up with a way you could design a tax that achieves this goal **without explicitly taxing stores based on size or county critera.** The liqour board does not want to obviously punish larger stores or speific counties for fear of backlash, but is willing to tax hard alcohol more than beer, for example.

Feel free to do more EDA if it helps.

Your report should describe whether such a tax is possible or not, and the specifics of what the tax will target/do.

In [97]:
Iowamerged2.groupby(['Store Number','VolumeSold_gallons'], sort=True)[['Profit_x']].sum().sort_values(by=['Profit_x'], ascending=False).reset_index()

Store Number  VolumeSold_gallons      Profit_x
0              2633                3.17  1.468794e+08
1              2633                2.38  1.398693e+08
2              4829                2.38  1.196244e+08
3              2633                0.20  8.712621e+07
4              4829                3.17  7.740401e+07
5              4829                6.34  5.512103e+07
6              2512                2.38  4.848964e+07
7              2633                6.34  4.773582e+07
8              2633                1.19  4.640055e+07
9              4829                9.51  3.635643e+07
10             4829                1.19  2.961290e+07
11             3952                3.17  2.803001e+07
12             4829                4.76  2.726732e+07
13             4829                0.40  2.697412e+07
14             2512                3.17  2.606668e+07
15             2633                9.51  2.603772e+07
16             4829               15.85  2.345576e+07
17             3773                3.17  2.341257e+07
18             2670                2.38  2.331531e+07
19             2512                1.19  2.242295e+07
20             2512                2.77  2.102152e+07
21             2633                2.77  2.069665e+07
22             2633               12.68  1.869375e+07
23             2663                2.38  1.726112e+07
24             4829               12.68  1.612583e+07
25             2501                2.38  1.593371e+07
26             3952                2.38  1.579469e+07
27             2670                3.17  1.556886e+07
28             3773                0.59  1.550502e+07
29             3385                3.17  1.538000e+07
...             ...                 ...           ...
17435          4563                0.99  8.131600e+02
17436          4563                0.53  8.131600e+02
17437          4831                0.59  7.450900e+02
17438          4831                0.20  7.450900e+02
17439          4831                1.19  7.450900e+02
17440          4831                4.76  7.450900e+02
17441          4917                0.40  7.412900e+02
17442          4917                0.99  7.412900e+02
17443          4917                0.08  7.412900e+02
17444          4917                0.24  7.412900e+02
17445          4917                0.30  7.412900e+02
17446          4917                0.32  7.412900e+02
17447          4917                0.53  7.412900e+02
17448          4917                0.69  7.412900e+02
17449          4917                1.98  7.412900e+02
17450          4917                1.06  7.412900e+02
17451          4917                1.59  7.412900e+02
17452          4917                8.32  7.412900e+02
17453          4927                0.16  7.219200e+02
17454          4927                0.20  7.219200e+02
17455          4927                0.30  7.219200e+02
17456          4927                0.32  7.219200e+02
17457          4927                0.69  7.219200e+02
17458          4927                1.85  7.219200e+02
17459          4635                1.06  7.136500e+02
17460          4635                0.13  7.136500e+02
17461          4635                0.48  7.136500e+02
17462          4635                0.59  7.136500e+02
17463          4635                0.66  7.136500e+02
17464          4635                2.54  7.136500e+02

[17465 rows x 3 columns]

In my opnion progressive taxation policy based on profit will be appropriate, as this needs that firms are made to pay more tax with increasing profitability. In this particlular case the correlation matrix shows that store size (volume sold in gallons) has high correlation with sales and also profit. This implies big stores earn more, so this policy ensures they pay fair tax, small firms with smaller profit margins would pay lower rates.


## 6. Case 2 = Market research for new store locations 

A liquor store owner in Iowa is looking to open a store in a new location and has hired you as a consultant to investigate the market data for potential new locations. The business owner is interested in what you can discover from the data that will help him evaluate a good location for a new storefront.

---

### 6.1 Create columns for Q1 2015 sales and Q1 2016 sales.

The owner is not just interested in what locations are currently selling well, but also which areas are showing the most promising sales growth from 2015 to 2016. 

For yearly changes we will focus on the changes from Q1 2015 to Q1 2016 specifically (avoiding effects of season changes).

Note: Q1 is months: January, February, and March.


In [98]:
Iowa2016=Iowa[Iowa['Year']==2016]
Iowa2016.head()

Date  Store Number         City Zip Code      County   Category  \
1  2016-03-02          2614    DAVENPORT    52807       Scott  1011100.0   
2  2016-02-11          2106  CEDAR FALLS    50613  Black Hawk  1011200.0   
3  2016-02-03          2501         AMES    50010       Story  1071100.0   
8  2016-01-04          4757    BONDURANT    50035        Polk  1032080.0   
13 2016-02-29          4673   WEST POINT    52656         Lee  1081300.0   

                Category Name  Item Number              Item Description  \
1            BLENDED WHISKIES        27605                       Tin Cup   
2   STRAIGHT BOURBON WHISKIES        19067                      Jim Beam   
3          AMERICAN COCKTAILS        59154       1800 Ultimate Margarita   
8              IMPORTED VODKA        34006  Absolut Swedish Vodka 80 Prf   
13        PEPPERMINT SCHNAPPS        75211                 Kinky Liqueur   

    Bottle Volume (ml)  State Bottle Cost  State Bottle Retail  Bottles Sold  \
1                  750              13.75                20.63             2   
2                 1000              12.59                18.89            24   
3                 1750               9.50                14.25             6   
8                  750              11.49                17.24             4   
13                 750              10.00                15.00            12   

    Sale (Dollars)  Volume Sold (Liters)  Volume Sold (Gallons)  Month  Year  
1            41.26                   1.5                   0.40      3  2016  
2           453.36                  24.0                   6.34      2  2016  
3            85.50                  10.5                   2.77      2  2016  
8            68.96                   3.0                   0.79      1  2016  
13          180.00                   9.0                   2.38      2  2016

In [99]:
Iowa2015.head()

Date  Store Number          City Zip Code County   Category  \
12 2015-01-22          3858     DAVENPORT    52806  Scott  1012100.0   
19 2015-03-04          2614     DAVENPORT    52807  Scott  1012100.0   
20 2015-01-16          2590  CEDAR RAPIDS    52402   Linn  1031200.0   
21 2015-01-13          3942        TOLEDO    52342   Tama  1012100.0   
22 2015-03-24          3981  SIOUX CENTER    51250  Sioux  1011100.0   

        Category Name  Item Number              Item Description  \
12  CANADIAN WHISKIES        15248          Windsor Canadian Pet   
19  CANADIAN WHISKIES        13638  Lord Calvert Canadian Whisky   
20     VODKA FLAVORED        41474          44 North Huckleberry   
21  CANADIAN WHISKIES        11786         Black Velvet Traveler   
22   BLENDED WHISKIES        25606   Seagrams 7 Crown Bl Whiskey   

    Bottle Volume (ml)  State Bottle Cost  State Bottle Retail  Bottles Sold  \
12                1750               8.92                13.38             1   
19                1750               9.97                14.96             6   
20                 750              14.25                21.38             2   
21                 750               5.23                 7.85            12   
22                 750               7.00                10.50            12   

    Sale (Dollars)  Volume Sold (Liters)  Volume Sold (Gallons)  Month  Year  
12           13.38                  1.75                   0.46      1  2015  
19           89.76                 10.50                   2.77      3  2015  
20           42.76                  1.50                   0.40      1  2015  
21           94.20                  9.00                   2.38      1  2015  
22          126.00                  9.00                   2.38      3  2015

In [100]:
Iowa2015= Iowa2015[(Iowa2015.Month <4)]

In [101]:
Q12015=Iowa2015.groupby(['County','Category Name'], sort=True)[['Sale (Dollars)']].sum().sort_values(by=['Sale (Dollars)'], ascending=False).reset_index()
Q12015.rename(columns={'Sale (Dollars)':'2015Sales'}, inplace=True)

In [102]:
Q12016=Iowa2016.groupby(['County','Category Name'], sort=True)[['Sale (Dollars)']].sum().sort_values(by=['Sale (Dollars)'], ascending=False).reset_index()
Q12016.rename(columns={'Sale (Dollars)':'2016Sales'}, inplace=True)

In [103]:
Iowafirstquarter=pd.merge(Q12015,Q12016,on=['County'],how='right')

Iowafirstquarter.head()

County            Category Name_x  2015Sales Category Name_y  2016Sales
0   Polk             VODKA 80 PROOF  162798.12  VODKA 80 PROOF  168785.85
1   Polk          CANADIAN WHISKIES  128093.97  VODKA 80 PROOF  168785.85
2   Polk                 SPICED RUM  108062.83  VODKA 80 PROOF  168785.85
3   Polk  STRAIGHT BOURBON WHISKIES   92603.32  VODKA 80 PROOF  168785.85
4   Polk             IMPORTED VODKA   82438.46  VODKA 80 PROOF  168785.85

### 6.2 Decide on a metric for performance that combines Q1 2016 sales as well as growth in sales from Q1 2015.

Again, the owner wants to know that his store will be in a good position to sell a large amount of liquor now, but also have his store be more likely to grow and sell even more going forward. 

In particular, he is worried about opening a store in an area that is showing a decline in liquor sales between Q1 2015 and Q1 2016.

In [104]:
Iowafirstquarter['New_sales'] = Iowafirstquarter['2016Sales']-Iowafirstquarter['2015Sales']
Iowafirstquarter.head()

County            Category Name_x  2015Sales Category Name_y  2016Sales  \
0   Polk             VODKA 80 PROOF  162798.12  VODKA 80 PROOF  168785.85   
1   Polk          CANADIAN WHISKIES  128093.97  VODKA 80 PROOF  168785.85   
2   Polk                 SPICED RUM  108062.83  VODKA 80 PROOF  168785.85   
3   Polk  STRAIGHT BOURBON WHISKIES   92603.32  VODKA 80 PROOF  168785.85   
4   Polk             IMPORTED VODKA   82438.46  VODKA 80 PROOF  168785.85   

   New_sales  
0    5987.73  
1   40691.88  
2   60723.02  
3   76182.53  
4   86347.39

In [105]:
# For calculating Growth

Iowafirstquarter['growth'] = Iowafirstquarter['New_sales']/Iowafirstquarter['2015Sales']
Iowafirstquarter.head()

County            Category Name_x  2015Sales Category Name_y  2016Sales  \
0   Polk             VODKA 80 PROOF  162798.12  VODKA 80 PROOF  168785.85   
1   Polk          CANADIAN WHISKIES  128093.97  VODKA 80 PROOF  168785.85   
2   Polk                 SPICED RUM  108062.83  VODKA 80 PROOF  168785.85   
3   Polk  STRAIGHT BOURBON WHISKIES   92603.32  VODKA 80 PROOF  168785.85   
4   Polk             IMPORTED VODKA   82438.46  VODKA 80 PROOF  168785.85   

   New_sales    growth  
0    5987.73  0.036780  
1   40691.88  0.317672  
2   60723.02  0.561923  
3   76182.53  0.822676  
4   86347.39  1.047416

Explain:

### 6.3 Recommend a location based on your metric.

The owner asks you to make a recommendation for a new store location. Explain why you recommended this area.

In [106]:
Iowafirstquarter.sort(['growth'],ascending=[False])

C:\Users\abhaindurkar\Anaconda3\New folder\envs\econ\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


County                     Category Name_x  2015Sales  \
65              Polk                  SPEARMINT SCHNAPPS       7.50   
131             Polk                  SPEARMINT SCHNAPPS       7.50   
197             Polk                  SPEARMINT SCHNAPPS       7.50   
263             Polk                  SPEARMINT SCHNAPPS       7.50   
329             Polk                  SPEARMINT SCHNAPPS       7.50   
395             Polk                  SPEARMINT SCHNAPPS       7.50   
461             Polk                  SPEARMINT SCHNAPPS       7.50   
8579           Scott                            ANISETTE       7.13   
527             Polk                  SPEARMINT SCHNAPPS       7.50   
593             Polk                  SPEARMINT SCHNAPPS       7.50   
659             Polk                  SPEARMINT SCHNAPPS       7.50   
22964  Pottawattamie                     CREME DE ALMOND       6.75   
725             Polk                  SPEARMINT SCHNAPPS       7.50   
23020  Pottawattamie                     CREME DE ALMOND       6.75   
791             Polk                  SPEARMINT SCHNAPPS       7.50   
857             Polk                  SPEARMINT SCHNAPPS       7.50   
47095         Dallas                      PEACH BRANDIES       7.92   
8641           Scott                            ANISETTE       7.13   
923             Polk                  SPEARMINT SCHNAPPS       7.50   
989             Polk                  SPEARMINT SCHNAPPS       7.50   
1055            Polk                  SPEARMINT SCHNAPPS       7.50   
35030    Cerro Gordo                  AMERICAN SLOE GINS       7.13   
35031    Cerro Gordo               WHITE CREME DE MENTHE       7.13   
29997        Dubuque                          ROCK & RYE       7.40   
23076  Pottawattamie                     CREME DE ALMOND       6.75   
22963  Pottawattamie                      GRAPE SCHNAPPS      11.43   
8578           Scott                     CHERRY BRANDIES      16.14   
16448       Woodbury                      GRAPE SCHNAPPS      11.43   
8703           Scott                            ANISETTE       7.13   
1121            Polk                  SPEARMINT SCHNAPPS       7.50   
...              ...                                 ...        ...   
4433            Polk                  TENNESSEE WHISKIES   41251.91   
4432            Polk             IMPORTED GRAPE BRANDIES   41508.59   
4290            Polk                      VODKA 80 PROOF  162798.12   
4360            Polk                      IMPORTED VODKA   82438.46   
19255       Woodbury                   CANADIAN WHISKIES   24357.71   
16333     Black Hawk                             TEQUILA   22539.56   
4431            Polk                      VODKA FLAVORED   46534.86   
4359            Polk           STRAIGHT BOURBON WHISKIES   92603.32   
4430            Polk               IMPORTED VODKA - MISC   50080.16   
26101  Pottawattamie                   CANADIAN WHISKIES   32411.83   
22849          Story                      VODKA 80 PROOF   32859.04   
41218         Warren                   CANADIAN WHISKIES   19590.25   
4358            Polk                          SPICED RUM  108062.83   
16268     Black Hawk                          SPICED RUM   31675.28   
4429            Polk  MISC. IMPORTED CORDIALS & LIQUEURS   59995.22   
19254       Woodbury                          SPICED RUM   33915.06   
16332     Black Hawk                          SPICED RUM   31675.28   
16267     Black Hawk                   CANADIAN WHISKIES   36417.57   
4357            Polk                   CANADIAN WHISKIES  128093.97   
4428            Polk                     WHISKEY LIQUEUR   68020.46   
16266     Black Hawk                      VODKA 80 PROOF   39980.68   
16331     Black Hawk                   CANADIAN WHISKIES   36417.57   
4427            Polk                             TEQUILA   75885.27   
16330     Black Hawk                      VODKA 80 PROOF   39980.68   
4426            Polk                  

I would suggest the POLK county based on the growth of sales, which accroding to the table is highest.

### 6.4 Recommend a location based also on a restricted inventory type.

Your employer has now decided he wants his store to focus on one type of liquor only. He askes you:

1. What would be the best type of liquor to sell to maximize profit?
2. Should the recommended location change if he is only selling one type of liquor?

In [107]:
Iowafirstquarter.head()

County            Category Name_x  2015Sales Category Name_y  2016Sales  \
0   Polk             VODKA 80 PROOF  162798.12  VODKA 80 PROOF  168785.85   
1   Polk          CANADIAN WHISKIES  128093.97  VODKA 80 PROOF  168785.85   
2   Polk                 SPICED RUM  108062.83  VODKA 80 PROOF  168785.85   
3   Polk  STRAIGHT BOURBON WHISKIES   92603.32  VODKA 80 PROOF  168785.85   
4   Polk             IMPORTED VODKA   82438.46  VODKA 80 PROOF  168785.85   

   New_sales    growth  
0    5987.73  0.036780  
1   40691.88  0.317672  
2   60723.02  0.561923  
3   76182.53  0.822676  
4   86347.39  1.047416

In [108]:
Iowa2015_2016 = Iowa2015.append(Iowa2016, ignore_index=True)

In [109]:
Iowa2015_2016.head()

Date  Store Number          City Zip Code County   Category  \
0 2015-01-22          3858     DAVENPORT    52806  Scott  1012100.0   
1 2015-03-04          2614     DAVENPORT    52807  Scott  1012100.0   
2 2015-01-16          2590  CEDAR RAPIDS    52402   Linn  1031200.0   
3 2015-01-13          3942        TOLEDO    52342   Tama  1012100.0   
4 2015-03-24          3981  SIOUX CENTER    51250  Sioux  1011100.0   

       Category Name  Item Number              Item Description  \
0  CANADIAN WHISKIES        15248          Windsor Canadian Pet   
1  CANADIAN WHISKIES        13638  Lord Calvert Canadian Whisky   
2     VODKA FLAVORED        41474          44 North Huckleberry   
3  CANADIAN WHISKIES        11786         Black Velvet Traveler   
4   BLENDED WHISKIES        25606   Seagrams 7 Crown Bl Whiskey   

   Bottle Volume (ml)  State Bottle Cost  State Bottle Retail  Bottles Sold  \
0                1750               8.92                13.38             1   
1                1750               9.97                14.96             6   
2                 750              14.25                21.38             2   
3                 750               5.23                 7.85            12   
4                 750               7.00                10.50            12   

   Sale (Dollars)  Volume Sold (Liters)  Volume Sold (Gallons)  Month  Year  
0           13.38                  1.75                   0.46      1  2015  
1           89.76                 10.50                   2.77      3  2015  
2           42.76                  1.50                   0.40      1  2015  
3           94.20                  9.00                   2.38      1  2015  
4          126.00                  9.00                   2.38      3  2015

In [115]:
Iowa2015_2016 = Iowa2015_2016.rename(index=str, columns={ "Sale (Dollars)": "Sale_Dollars", "State Bottle Cost": "State_Bottle_Cost", "State Bottle Retail": "State_Bottle_Retail", "Bottles Sold": "Bottles_Sold"})

In [119]:
Iowa2015_2016sales = Iowa2015_2016.groupby(['Store Number','County'])['Sale_Dollars'].sum().reset_index()
Iowa2015_2016sales.head()

Store Number       County  Sale_Dollars
0          2106   Black Hawk      69811.04
1          2113      Webster       4899.15
2          2130   Black Hawk      52128.68
3          2152  Cerro Gordo       2908.12
4          2178    Allamakee      11444.91

In [121]:
Iowa2015_2016sales.sort(['Sale_Dollars'],ascending=[False])

C:\Users\abhaindurkar\Anaconda3\New folder\envs\econ\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


Store Number         County  Sale_Dollars
125           2633           Polk     426563.87
1029          4829           Polk     414182.24
36            2512        Johnson     194636.61
194           3385           Linn     170527.29
389           3952          Scott     144980.23
200           3420           Polk     136098.18
204           3447       Woodbury     129791.62
323           3814         Dallas     119562.60
306           3773           Linn     114777.73
153           2670        Johnson      94827.21
499           4167        Dubuque      87332.14
193           3354          Scott      84922.62
123           2629  Pottawattamie      82171.03
1264          5102           Linn      79769.40
119           2625          Scott      78697.01
134           2648           Polk      78460.73
327           3820       Woodbury      76590.89
6             2191            Lee      76423.77
28            2500          Story      74071.09
110           2614          Scott      71357.29
0             2106     Black Hawk      69811.04
209           3477  Pottawattamie      69325.86
216           3524          Story      65826.24
111           2616        Clinton      65023.31
32            2506     Des Moines      64051.20
5             2190           Polk      63968.61
590           4312  Pottawattamie      63174.38
55            2544       Marshall      62089.45
29            2501          Story      61393.49
212           3494     Black Hawk      60100.02
...            ...            ...           ...
1291          5130          Scott        246.40
338           3845        Webster        245.04
1271          5109         Warren        243.60
748           4513           Polk        242.42
1336          5182  Pottawattamie        232.18
1164          4996        Dubuque        222.64
766           4532    Buena Vista        221.28
330           3826         Clarke        214.56
1280          5118        Dubuque        213.92
903           4691         Hardin        196.38
1324          5170       Marshall        196.02
1130          4954           Polk        188.40
1337          5183        Dubuque        182.16
1300          5141        Webster        179.28
1344          5191        Guthrie        164.76
1016          4811         Monroe        157.06
948           4737    Buena Vista        148.68
1308          5150      Poweshiek        135.66
886           4672        Clayton        134.59
1031          4834      Muscatine        134.52
1139          4968      Poweshiek        115.44
433           4059         Benton        105.41
742           4507           Clay         98.64
1173          5006        Dubuque         94.50
1346          5195  Pottawattamie         92.50
1332          5178      Muscatine         83.94
1342          5189           Polk         68.40
1117          4939           Polk         53.40
1345          5192           Linn         33.60
798           4567           Polk         13.75

[1365 rows x 3 columns]

As we saw earier that profit is highly correlated with sales, here we see that Polk has highest demand of the liquor. The location should be changed if there is low or no demand in case the store has access only that type of liquor, however if the store has access for various kinds of liquor then, the location with highest demand will lead to higher profits, which in this case is POLK county.

The commands for this data analysis come from Stack Overflow Community, Modern Pandas, Panda tutorials, Panda doccumentation and youtube channel.